In [1]:
import math
import torch
import torch.nn as nn

In [20]:
m = nn.Linear(20, 20)
m

Linear(in_features=20, out_features=20, bias=True)

In [21]:
input = torch.randn(2, 20)
input

tensor([[ 1.2326,  0.1785, -1.2490, -0.7306, -0.2291,  0.5594, -1.5559, -1.0116,
         -1.1620, -1.0997, -0.2715, -0.4577, -0.2467,  1.1738, -0.8826, -1.0207,
          0.4757, -0.5631, -1.6778, -0.7757],
        [-0.1527, -1.1700, -1.4510, -0.0490,  1.1780,  0.4239,  0.2479, -1.3563,
          0.0314, -0.6898, -0.0330, -0.0472,  0.8067,  0.5678,  1.2402, -1.0382,
          0.1232, -1.3979,  2.4194, -1.2689]])

In [22]:
print(m(input))

tensor([[-0.1000, -0.4543, -0.4174,  1.0990, -0.0654,  0.1410, -0.1766,  0.6177,
          0.1771, -0.3112,  0.5409, -0.2009, -0.3068,  0.1291, -0.1453,  0.3107,
         -0.0550,  0.2477,  0.6072, -0.0276],
        [-0.4808,  0.9679, -0.5283, -0.8774, -0.1210, -0.4861, -0.4526,  0.0085,
          0.4329,  0.1407, -0.7759, -0.4490, -0.2439,  0.4977,  0.2351, -0.0262,
          0.1187, -0.8186,  0.5970, -0.3676]], grad_fn=<AddmmBackward0>)


In [23]:
tensor1 = torch.randn(1, 3, 4)
print(tensor1)
tensor2 = torch.randn(4, 5)
print(tensor2)
output = torch.matmul(tensor1, tensor2)
print(output)

tensor([[[ 2.1027, -0.8514, -1.8332, -0.9616],
         [-0.0031, -0.2130,  1.0061,  0.1961],
         [ 0.1619, -0.6942, -2.0076, -0.3162]]])
tensor([[-1.7367, -0.0734,  0.9158,  0.2476,  1.3631],
        [-0.4264,  0.3656, -0.9017, -0.4464,  0.3248],
        [ 0.2003,  0.3338, -0.4573,  1.0601,  1.5355],
        [ 0.2081, -0.6021, -0.0551,  1.4546, -0.0076]])
tensor([[[-3.8560, -0.4986,  3.5846, -2.4414, -0.2180],
         [ 0.3385,  0.1401, -0.2817,  1.4463,  1.4701],
         [-0.4531, -0.7454,  1.7097, -2.2381, -3.0850]]])


In [26]:
tensor1 = torch.tensor(
    [[1, 4],
    [2, 5],
    [3, 6]]
)

tensor2 = torch.tensor(
    [[2, 1],
    [1, 2]]
)

print(torch.matmul(tensor1, tensor2))

tensor([[ 6,  9],
        [ 9, 12],
        [12, 15]])


# transpose test

In [34]:
x = torch.randn(3, 2, 3)
print(x)
x2 = torch.transpose(x, 0, 1)
print(x2)
print(x2.size())

tensor([[[ 1.0804,  0.6381, -1.5405],
         [-0.2551, -0.2482,  1.1230]],

        [[-0.5511, -0.7775, -1.2440],
         [-1.1035,  1.0970, -0.0220]],

        [[-1.1994, -0.1375,  0.3712],
         [-0.4051,  0.2625,  1.8980]]])
tensor([[[ 1.0804,  0.6381, -1.5405],
         [-0.5511, -0.7775, -1.2440],
         [-1.1994, -0.1375,  0.3712]],

        [[-0.2551, -0.2482,  1.1230],
         [-1.1035,  1.0970, -0.0220],
         [-0.4051,  0.2625,  1.8980]]])
torch.Size([2, 3, 3])


In [3]:
import torch
import torch.nn as nn

# Input tensor
input_tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

# Softmax along dim=0 (column-wise)
softmax_dim0 = nn.Softmax(dim=0)
output_dim0 = softmax_dim0(input_tensor)
print("Softmax dim=0:\n", output_dim0)

# Softmax along dim=1 (row-wise)
softmax_dim1 = nn.Softmax(dim=1)
output_dim1 = softmax_dim1(input_tensor)
print("Softmax dim=1:\n", output_dim1)

Softmax dim=0:
 tensor([[0.1192, 0.1192],
        [0.8808, 0.8808]])
Softmax dim=1:
 tensor([[0.2689, 0.7311],
        [0.2689, 0.7311]])
