In [7]:
import torch

x = torch.randn(3, 4, requires_grad=True)
x

tensor([[-0.5198, -1.7938, -1.0099,  0.4462],
        [ 0.1853, -1.3639,  0.7800,  1.8042],
        [ 0.4307,  0.9735,  0.3887, -1.1974]], requires_grad=True)

In [8]:
b = torch.randn(3, 4, requires_grad=True)
b

tensor([[-1.8023, -0.0634, -0.7808, -0.4731],
        [ 0.4215, -0.5878,  0.7289, -0.8650],
        [-1.3651, -1.6284,  0.3512,  1.1805]], requires_grad=True)

In [9]:
t = x + b
t

tensor([[-2.3221, -1.8572, -1.7907, -0.0269],
        [ 0.6067, -1.9516,  1.5090,  0.9393],
        [-0.9344, -0.6549,  0.7399, -0.0169]], grad_fn=<AddBackward0>)

In [10]:
y = t.sum()
y

tensor(-5.7599, grad_fn=<SumBackward0>)

In [11]:
b.grad

In [12]:
y.backward()
y

tensor(-5.7599, grad_fn=<SumBackward0>)

只需要在最后一步的时候调用这个反向传播函数就可以了，这个函数会自动计算出所有的梯度，然后我们就可以使用这些梯度来更新我们的参数。

In [13]:
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
x.requires_grad, b.requires_grad, t.requires_grad, y.requires_grad

(True, True, True, True)